language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  # Install binary pandoc from Rstudio
  - mkdir -p $HOME/opt/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
    -d $HOME/opt/pandoc
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc-citeproc
    -d $HOME/opt/pandoc-citeproc
  - chmod +x $HOME/opt/pandoc/pandoc*
  - rm pandoc-1.12.3.zip
  - $HOME/opt/pandoc/pandoc --version
  
  
  # Install R packages
  - ./travis-tool.sh r_binary_install knitr ggplot2 jpeg mgcv
  - ./travis-tool.sh r_install        rvest magrittr gridExtra dplyr plyr tidyr xtable splines nlme effects broom
  - ./travis-tool.sh github_package   rstudio/rmarkdown hadley/bookdown adletaw/captioner/captioner

script: make


notifications:
  email:
    on_success: change
    on_failure: change
