language: r

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages:
  - hadley/bookdown 
  - hadley/ggplot2
  - adletaw/captioner

script: 
  # hyperref needs to be 6.83a or lower -- https://github.com/hadley/ggplot2-book/issues/32
  - head `kpsewhich hyperref.sty` -n 29 | tail -n 4
  - pandoc --version
  - pandoc-citeproc --version
  # Install xelatex
  - sudo apt-get install texlive-xetex
  - xelatex -version
  # Install inconsolata
  - sudo apt-get install fonts-inconsolata
  - sudo fc-cache -fv
  # Build book
  - make

notifications:
  email:
    on_success: change
    on_failure: change
